[tool.poetry]
name = "takeda"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
matplotlib = "^3.6.1"
pandas = "^1.5.0"
scipy = "*"
seaborn = "^0.12.0"
pot = "^0.8.2"
jupyter = "^1.0.0"
sklearn = "^0.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
sphinx = "^5.3.0"
pulp = "^2.6.0"
tqdm = "^4.64.1"
optuna = "^3.0.5"
pymysql = "^1.0.2"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
