[tool.poetry]
name = "takeda"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
matplotlib = "^3.6.1"
pandas = "^1.5.0"
scipy = "*"
seaborn = "^0.12.0"
pot = "0.9.0"
jupyter = "^1.0.0"
# sklearn = "^0.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
sphinx = "^5.3.0"
pulp = "^2.6.0"
tqdm = "^4.64.1"
optuna = "^3.2.0"
pymysql = "^1.0.2"
scikit-learn = "*"
pysqlite3 = "^0.5.0"
plotly = "^5.13.1"
jax = "^0.4.6"
jaxlib = "^0.4.6"
rsatoolbox = "^0.1.2"
cryptography = "^40.0.1"
sqlalchemy = "^2.0.9"
django = "^4.2"
sqlalchemy-utils = "^0.41.1"
torch = "^2.0.1"

[poetry.group.dev.dependencies]
autopep8 = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pyproject-flake8 = "5.0.4"
flake8-isort = "^6.0.0"
flake8-bugbear = "^23.1.20"
flake8-builtins = "^2.1.0"
flake8-unused-arguments = "^0.0.12"
flake8-pytest-style = "^1.6.0"
pep8-naming = "^0.13.3"
mypy = "^0.991"
black = "^22.12.0"
isort = "^5.12.0"
flake8-eradicate = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
# エラー時のメッセージを詳細表示
show_error_context = true
# エラー発生箇所の行数/列数を表示
show_column_numbers = true
# import 先のチェックを行わない (デフォルトだとサードパーティーライブラリまでチェックする)
ignore_missing_imports = true
# 関数定義の引数/戻り値に型アノテーション必須
disallow_untyped_defs = true
# デフォルト引数に None を取る場合型アノテーションに Optional 必須
no_implicit_optional = true
# 戻り値が Any 型ではない関数の戻り値の型アノテーションが Any のとき警告
warn_return_any = true
# mypy エラーに該当しない箇所に `# type: ignore` コメントが付与されていたら警告
# ※ `# type: ignore` が付与されている箇所は mypy のエラーを無視出来る
warn_unused_ignores = true
# 冗長なキャストに警告
warn_redundant_casts = true

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
# 各ライブラリ群の説明を追記する
import_heading_stdlib      = "Standard Library"
import_heading_thirdparty  = "Third Party Library"
import_heading_firstparty  = "First Party Library"
import_heading_localfolder = "Local Library"
# from third_party import lib1, lib2...のような記述時の改行方法の設定(https://pycqa.github.io/isort/docs/configuration/multi_line_output_modes.html)
multi_line_output = 3
# 最後の要素の末尾に","を付けるようにする設定
include_trailing_comma = true

[tool.flake8]
max-line-length = 120
# E203: ":"の前の空白を入れないルール
# W503: 演算子の前に改行しないようにするルール
# F401: import していないが使っていないものへの警告
extend-ignore = ["E203", "W503", "F401"]
exclude = [".venv", ".git", "__pycache__",]
max-complexity = 10
